// استيراد الأدوات اللازمة من مكتبة MongoDB
const { MongoClient, ObjectId } = require('mongodb');

// ======================= معلومات الاتصال =======================
const uri = "mongodb+srv://majoriyad:ohX8v7WGQEfI56GR@cluster0.bpqezif.mongodb.net/";
const dbName = 'test';
const collectionName = 'questions';

// ======================= استخراج الـ ObjectIds =======================
const academicLevelId = '6856e57742d2333b081f4375';
const trackId = '6856e5b242d2333b081f4386';
const subjectId = '6856e8f242d2333b081f44fd';

// ======================= قائمة الأسئلة (الجزء الثاني: 35-67) =======================
const questionsToInsert = [
  // ########## Unité 1 : Métabolisme (Nouveaux et variés) ##########
  {
    academicLevel: new ObjectId(academicLevelId),
    track: new ObjectId(trackId),
    subject: new ObjectId(subjectId),
    level: 'متوسط',
    type: 'mcq',
    text: "La décarboxylation oxydative du pyruvate a lieu dans :",
    options: [
      "Le hyaloplasme, avant l'entrée dans la mitochondrie",
      "La membrane externe de la mitochondrie",
      "L'espace intermembranaire de la mitochondrie",
      "La matrice mitochondriale",
    ],
    correctAnswer: "La matrice mitochondriale",
    lesson: "Consommation de la matière organique et flux d'énergie",
    generatedBy: 'db',
  },
  {
    academicLevel: new ObjectId(academicLevelId),
    track: new ObjectId(trackId),
    subject: new ObjectId(subjectId),
    level: 'صعب',
    type: 'mcq',
    text: "Le dinitrophénol (DNP) est un agent découplant qui rend la membrane interne de la mitochondrie perméable aux protons \\\\(H^+\\\\). Quel sera l'effet de l'ajout de DNP à une suspension de mitochondries ?",
    options: [
      "La synthèse d'ATP s'arrête, mais la consommation d'oxygène continue, voire augmente",
      "La synthèse d'ATP et la consommation d'oxygène s'arrêtent toutes les deux",
      "La synthèse d'ATP continue, mais la consommation d'oxygène s'arrête",
      "La glycolyse est immédiatement inhibée",
    ],
    correctAnswer: "La synthèse d'ATP s'arrête, mais la consommation d'oxygène continue, voire augmente",
    lesson: "Consommation de la matière organique et flux d'énergie",
    generatedBy: 'db',
  },
  {
    academicLevel: new ObjectId(academicLevelId),
    track: new ObjectId(trackId),
    subject: new ObjectId(subjectId),
    level: 'متوسط',
    type: 'mcq',
    text: "L'énergie libérée lors du passage des électrons le long de la chaîne respiratoire est utilisée pour :",
    options: [
      "Phosphoryler directement l'ADP en ATP",
      "Pomper des protons (H+) de la matrice vers l'espace intermembranaire",
      "Réduire le dioxygène en eau",
      "Oxyder le glucose en pyruvate",
    ],
    correctAnswer: "Pomper des protons (H+) de la matrice vers l'espace intermembranaire",
    lesson: "Consommation de la matière organique et flux d'énergie",
    generatedBy: 'db',
  },
  {
    academicLevel: new ObjectId(academicLevelId),
    track: new ObjectId(trackId),
    subject: new ObjectId(subjectId),
    level: 'سهل',
    type: 'mcq',
    text: "La contraction musculaire intense et de courte durée dépend principalement de l'énergie fournie par :",
    options: [
      "La respiration cellulaire aérobie",
      "Les réserves d'ATP et la phosphocréatine, suivies de la fermentation lactique",
      "L'oxydation des acides gras",
      "La fermentation alcoolique",
    ],
    correctAnswer: "Les réserves d'ATP et la phosphocréatine, suivies de la fermentation lactique",
    lesson: "Consommation de la matière organique et flux d'énergie",
    generatedBy: 'db',
  },
  {
    academicLevel: new ObjectId(academicLevelId),
    track: new ObjectId(trackId),
    subject: new ObjectId(subjectId),
    level: 'متوسط',
    type: 'free_text',
    text: "Quel est le devenir des transporteurs réduits (\\\\(NADH,H^+\\\\) et \\\\(FADH_2\\\\)) produits lors de la glycolyse et du cycle de Krebs dans une cellule en aérobiose ?",
    options: [],
    correctAnswer: '-',
    lesson: "Consommation de la matière organique et flux d'énergie",
    generatedBy: 'db',
  },
  {
    academicLevel: new ObjectId(academicLevelId),
    track: new ObjectId(trackId),
    subject: new ObjectId(subjectId),
    level: 'صعب',
    type: 'free_text',
    text: "Proposez un protocole expérimental simple pour démontrer que la fermentation lactique dans un extrait musculaire produit de l'acide lactique et consomme du glucose.",
    options: [],
    correctAnswer: '-',
    lesson: "Consommation de la matière organique et flux d'énergie",
    generatedBy: 'db',
  },

  // ########## Unité 2 : Info Génétique (Nouveaux et variés) ##########
  {
    academicLevel: new ObjectId(academicLevelId),
    track: new ObjectId(trackId),
    subject: new ObjectId(subjectId),
    level: 'متوسط',
    type: 'mcq',
    text: "Dans la double hélice d'ADN, l'adénine (A) est toujours appariée avec la thymine (T) par :",
    options: [
      "Une liaison hydrogène",
      "Deux liaisons hydrogène",
      "Trois liaisons hydrogène",
      "Une liaison covalente",
    ],
    correctAnswer: "Deux liaisons hydrogène",
    lesson: "Nature de l'information génétique et son mécanisme d'expression",
    generatedBy: 'db',
  },
  {
    academicLevel: new ObjectId(academicLevelId),
    track: new ObjectId(trackId),
    subject: new ObjectId(subjectId),
    level: 'متوسط',
    type: 'mcq',
    text: "Le dogme central de la biologie moléculaire postule que le flux d'information génétique se fait selon l'ordre :",
    options: [
      "Protéine -> ARN -> ADN",
      "ARN -> ADN -> Protéine",
      "ADN -> Protéine -> ARN",
      "ADN -> ARN -> Protéine",
    ],
    correctAnswer: "ADN -> ARN -> Protéine",
    lesson: "Nature de l'information génétique et son mécanisme d'expression",
    generatedBy: 'db',
  },
  {
    academicLevel: new ObjectId(academicLevelId),
    track: new ObjectId(trackId),
    subject: new ObjectId(subjectId),
    level: 'صعب',
    type: 'mcq',
    text: "Si un ARNm a la séquence 5'-AUG GCU UCA-3', quelle est la séquence du brin d'ADN non-transcrit (brin codant) correspondant ?",
    options: [
      "3'-TAC CGA AGT-5'",
      "5'-TAC CGA AGT-3'",
      "5'-ATG GCT TCA-3'",
      "3'-ATG GCT TCA-5'",
    ],
    correctAnswer: "5'-ATG GCT TCA-3'",
    lesson: "Nature de l'information génétique et son mécanisme d'expression",
    generatedBy: 'db',
  },
  {
    academicLevel: new ObjectId(academicLevelId),
    track: new ObjectId(trackId),
    subject: new ObjectId(subjectId),
    level: 'متوسط',
    type: 'mcq',
    text: "Une mutation faux-sens (missense) est une mutation qui :",
    options: [
      "N'a aucun effet sur la protéine",
      "Remplace un acide aminé par un autre",
      "Crée un codon STOP prématuré",
      "Décale le cadre de lecture",
    ],
    correctAnswer: "Remplace un acide aminé par un autre",
    lesson: "Nature de l'information génétique et son mécanisme d'expression",
    generatedBy: 'db',
  },
  {
    academicLevel: new ObjectId(academicLevelId),
    track: new ObjectId(trackId),
    subject: new ObjectId(subjectId),
    level: 'متوسط',
    type: 'free_text',
    text: "Décrivez les trois étapes principales de la traduction (initiation, élongation, terminaison).",
    options: [],
    correctAnswer: '-',
    lesson: "Nature de l'information génétique et son mécanisme d'expression",
    generatedBy: 'db',
  },

  // ########## Unité 3 : Lois statistiques (Nouveaux et variés) ##########
  {
    academicLevel: new ObjectId(academicLevelId),
    track: new ObjectId(trackId),
    subject: new ObjectId(subjectId),
    level: 'متوسط',
    type: 'mcq',
    text: "La division équationnelle de la méiose, qui ressemble à une mitose, est :",
    options: ["La prophase I", "L'anaphase I", "La méiose I dans son ensemble", "La méiose II dans son ensemble"],
    correctAnswer: "La méiose II dans son ensemble",
    lesson: "Transmission de l'information génétique et lois statistiques",
    generatedBy: 'db',
  },
  {
    academicLevel: new ObjectId(academicLevelId),
    track: new ObjectId(trackId),
    subject: new ObjectId(subjectId),
    level: 'متوسط',
    type: 'mcq',
    text: "Chez l'humain, un gamète (spermatozoïde ou ovule) normal contient :",
    options: ["46 chromosomes", "23 paires de chromosomes", "22 autosomes et un chromosome sexuel", "44 autosomes et deux chromosomes sexuels"],
    correctAnswer: "22 autosomes et un chromosome sexuel",
    lesson: "Transmission de l'information génétique et lois statistiques",
    generatedBy: 'db',
  },
  {
    academicLevel: new ObjectId(academicLevelId),
    track: new ObjectId(trackId),
    subject: new ObjectId(subjectId),
    level: 'صعب',
    type: 'mcq',
    text: "Chez une plante, l'allèle (R) pour les fleurs rouges est dominant sur l'allèle (r) pour les fleurs blanches. Un croisement entre deux plantes hétérozygotes (Rr x Rr) donne 120 descendants. Combien de descendants devraient avoir des fleurs blanches, statistiquement ?",
    options: ["120", "90", "60", "30"],
    correctAnswer: "30",
    lesson: "Transmission de l'information génétique et lois statistiques",
    generatedBy: 'db',
  },
  {
    academicLevel: new ObjectId(academicLevelId),
    track: new ObjectId(trackId),
    subject: new ObjectId(subjectId),
    level: 'متوسط',
    type: 'mcq',
    text: "Un père de groupe sanguin O et une mère de groupe sanguin AB ne peuvent pas avoir un enfant de groupe :",
    options: ["A", "B", "AB", "O"],
    correctAnswer: "O",
    lesson: "Transmission de l'information génétique et lois statistiques",
    generatedBy: 'db',
  },
  {
    academicLevel: new ObjectId(academicLevelId),
    track: new ObjectId(trackId),
    subject: new ObjectId(subjectId),
    level: 'صعب',
    type: 'mcq',
    text: "Deux gènes A et B sont liés. Un individu de génotype AB/ab produit 15% de gamètes recombinés (Ab et aB). Si on croise cet individu avec un individu ab/ab, quel pourcentage de la descendance aura un phénotype parental [ab] ?",
    options: ["15%", "35%", "42.5%", "85%"],
    correctAnswer: "42.5%",
    lesson: "Transmission de l'information génétique et lois statistiques",
    generatedBy: 'db',
  },
  {
    academicLevel: new ObjectId(academicLevelId),
    track: new ObjectId(trackId),
    subject: new ObjectId(subjectId),
    level: 'متوسط',
    type: 'free_text',
    text: "Qu'est-ce qu'un chiasma et quel est son rôle dans le brassage génétique ?",
    options: [],
    correctAnswer: '-',
    lesson: "Transmission de l'information génétique et lois statistiques",
    generatedBy: 'db',
  },
  {
    academicLevel: new ObjectId(academicLevelId),
    track: new ObjectId(trackId),
    subject: new ObjectId(subjectId),
    level: 'صعب',
    type: 'free_text',
    text: "Expliquez comment une non-disjonction des chromatides sœurs lors de l'anaphase II de la méiose peut conduire à des gamètes anormaux (aneuploïdes).",
    options: [],
    correctAnswer: '-',
    lesson: "Transmission de l'information génétique et lois statistiques",
    generatedBy: 'db',
  },

  // ########## Unité 5 : Géologie (Nouveaux et variés) ##########
  {
    academicLevel: new ObjectId(academicLevelId),
    track: new ObjectId(trackId),
    subject: new ObjectId(subjectId),
    level: 'متوسط',
    type: 'mcq',
    text: "Le magmatisme andésitique est caractéristique des :",
    options: ["Dorsales médio-océaniques", "Chaînes de subduction", "Rifts continentaux", "Points chauds sous plaque continentale"],
    correctAnswer: "Chaînes de subduction",
    lesson: "Les chaînes de montagnes récentes et la tectonique des plaques",
    generatedBy: 'db',
  },
  {
    academicLevel: new ObjectId(academicLevelId),
    track: new ObjectId(trackId),
    subject: new ObjectId(subjectId),
    level: 'متوسط',
    type: 'mcq',
    text: "Les structures tectoniques cassantes (failles) sont typiques d'un comportement :",
    options: ["Plastique en profondeur", "Fragile en surface ou à faible profondeur", "Ductile à haute température", "Élastique"],
    correctAnswer: "Fragile en surface ou à faible profondeur",
    lesson: "Les chaînes de montagnes récentes et la tectonique des plaques",
    generatedBy: 'db',
  },
  {
    academicLevel: new ObjectId(academicLevelId),
    track: new ObjectId(trackId),
    subject: new ObjectId(subjectId),
    level: 'صعب',
    type: 'mcq',
    text: "L'exhumation (remontée en surface) de roches métamorphiques de haute pression comme les éclogites est un phénomène complexe qui implique souvent :",
    options: [
      "Une augmentation de la vitesse de subduction",
      "Uniquement l'érosion de la chaîne de montagnes",
      "Des mécanismes tectoniques d'extension (effondrement gravitaire) après l'épaississement crustal",
      "Une reprise du magmatisme",
    ],
    correctAnswer: "Des mécanismes tectoniques d'extension (effondrement gravitaire) après l'épaississement crustal",
    lesson: "Les chaînes de montagnes récentes et la tectonique des plaques",
    generatedBy: 'db',
  },
  {
    academicLevel: new ObjectId(academicLevelId),
    track: new ObjectId(trackId),
    subject: new ObjectId(subjectId),
    level: 'سهل',
    type: 'mcq',
    text: "La chaîne des Andes est un exemple typique de chaîne de :",
    options: ["Collision", "Subduction", "Coulissage", "Rifting"],
    correctAnswer: "Subduction",
    lesson: "Les chaînes de montagnes récentes et la tectonique des plaques",
    generatedBy: 'db',
  },
  {
    academicLevel: new ObjectId(academicLevelId),
    track: new ObjectId(trackId),
    subject: new ObjectId(subjectId),
    level: 'متوسط',
    type: 'mcq',
    text: "Un granite est une roche magmatique plutonique, de texture grenue, riche en :",
    options: ["Pyroxène et olivine", "Quartz, feldspaths et micas", "Calcite et dolomite", "Basalte et gabbro"],
    correctAnswer: "Quartz, feldspaths et micas",
    lesson: "Les chaînes de montagnes récentes et la tectonique des plaques",
    generatedBy: 'db',
  },
  {
    academicLevel: new ObjectId(academicLevelId),
    track: new ObjectId(trackId),
    subject: new ObjectId(subjectId),
    level: 'متوسط',
    type: 'free_text',
    text: "Qu'est-ce qu'un prisme d'accrétion et comment se forme-t-il dans une zone de subduction ?",
    options: [],
    correctAnswer: '-',
    lesson: "Les chaînes de montagnes récentes et la tectonique des plaques",
    generatedBy: 'db',
  },
  {
    academicLevel: new ObjectId(academicLevelId),
    track: new ObjectId(trackId),
    subject: new ObjectId(subjectId),
    level: 'صعب',
    type: 'free_text',
    text: "Décrivez la succession des événements géologiques qui ont mené de la fermeture d'un océan (l'océan alpin) à la formation d'une chaîne de collision comme les Alpes.",
    options: [],
    correctAnswer: '-',
    lesson: "Les chaînes de montagnes récentes et la tectonique des plaques",
    generatedBy: 'db',
  },

  // ########## Questions de Synthèse (Nouveaux et variés) ##########
  {
    academicLevel: new ObjectId(academicLevelId),
    track: new ObjectId(trackId),
    subject: new ObjectId(subjectId),
    level: 'صعب',
    type: 'mcq',
    text: "La transformation d'un calcaire sédimentaire en marbre dans une chaîne de montagnes est un processus de :",
    options: [
      "Sédimentation",
      "Métamorphisme",
      "Magmatisme",
      "Érosion",
    ],
    correctAnswer: "Métamorphisme",
    lesson: "Synthèse Biologie & Géologie",
    generatedBy: 'db',
  },
  {
    academicLevel: new ObjectId(academicLevelId),
    track: new ObjectId(trackId),
    subject: new ObjectId(subjectId),
    level: 'متوسط',
    type: 'mcq',
    text: "Le brassage génétique qui a lieu durant la méiose a pour conséquence :",
    options: [
      "De créer de nouveaux gènes",
      "De créer de nouvelles combinaisons d'allèles sur les chromosomes",
      "De doubler le nombre de chromosomes",
      "D'empêcher les mutations",
    ],
    correctAnswer: "De créer de nouvelles combinaisons d'allèles sur les chromosomes",
    lesson: "Synthèse Biologie & Géologie",
    generatedBy: 'db',
  },
  {
    academicLevel: new ObjectId(academicLevelId),
    track: new ObjectId(trackId),
    subject: new ObjectId(subjectId),
    level: 'صعب',
    type: 'mcq',
    text: "La découverte de basaltes en coussins (pillow lavas) au sommet d'une montagne est un indice fort :",
    options: [
      "D'une éruption volcanique aérienne récente",
      "De la présence d'une ancienne croûte océanique qui a été charriée en altitude",
      "De la formation d'un granite en profondeur",
      "D'un métamorphisme de haute pression",
    ],
    correctAnswer: "De la présence d'une ancienne croûte océanique qui a été charriée en altitude",
    lesson: "Synthèse Biologie & Géologie",
    generatedBy: 'db',
  },
  {
    academicLevel: new ObjectId(academicLevelId),
    track: new ObjectId(trackId),
    subject: new ObjectId(subjectId),
    level: 'متوسط',
    type: 'mcq',
    text: "Quel processus biologique assure la conservation du caryotype (nombre et morphologie des chromosomes) de l'espèce au fil des générations ?",
    options: [
      "La mitose seule",
      "L'alternance de la méiose et de la fécondation",
      "La transcription",
      "Les mutations",
    ],
    correctAnswer: "L'alternance de la méiose et de la fécondation",
    lesson: "Synthèse Biologie & Géologie",
    generatedBy: 'db',
  },
  {
    academicLevel: new ObjectId(academicLevelId),
    track: new ObjectId(trackId),
    subject: new ObjectId(subjectId),
    level: 'متوسط',
    type: 'free_text',
    text: "Comment le cycle de Krebs et la chaîne respiratoire sont-ils couplés ? (Quelle est la molécule 'lien' entre les deux ?)",
    options: [],
    correctAnswer: '-',
    lesson: "Synthèse Biologie & Géologie",
    generatedBy: 'db',
  },
  {
    academicLevel: new ObjectId(academicLevelId),
    track: new ObjectId(trackId),
    subject: new ObjectId(subjectId),
    level: 'صعب',
    type: 'free_text',
    text: "Expliquez pourquoi deux gènes situés sur le même chromosome peuvent parfois se comporter comme s'ils étaient indépendants (selon les lois de Mendel).",
    options: [],
    correctAnswer: '-',
    lesson: "Synthèse Biologie & Géologie",
    generatedBy: 'db',
  },
  {
    academicLevel: new ObjectId(academicLevelId),
    track: new ObjectId(trackId),
    subject: new ObjectId(subjectId),
    level: 'صعب',
    type: 'free_text',
    text: "Décrivez un scénario plausible expliquant comment un fossile d'ammonite (animal marin) peut être retrouvé à 3000m d'altitude dans les Alpes. Intégrez les notions de sédimentation, tectonique des plaques, et orogenèse.",
    options: [],
    correctAnswer: '-',
    lesson: "Synthèse Biologie & Géologie",
    generatedBy: 'db',
  },
];

// ======================= دالة الاتصال والإضافة =======================
async function run() {
  const client = new MongoClient(uri);
  try {
    await client.connect();
    console.log("Part 2: Successfully connected to MongoDB Atlas!");
    const database = client.db(dbName);
    const collection = database.collection(collectionName);
    console.log(`Part 2: Attempting to insert ${questionsToInsert.length} new documents...`);
    const result = await collection.insertMany(questionsToInsert);
    console.log(`✅ Success! ${result.insertedCount} documents were inserted from Part 2.`);
  } catch (err) {
    console.error("❌ An error occurred during Part 2 insertion:", err);
  } finally {
    await client.close();
    console.log("Part 2: Connection to MongoDB closed.");
  }
}

// تشغيل الدالة الرئيسية
run().catch(console.dir);